### ISSUE TITLE
YunoHost diagnosis: "Port 8098 is not reachable from outside" after uninstalling Wireguard

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/wireguard_ynh#12]
### Describe the bug

After uninstalling Wireguard, YunoHost's automatic diagnosis insists that there is a port assigned to Wireguard that is not reachable from outside.

### Context

- Hardware: Raspberry Pi 4
- YunoHost version: 4.1.7.3
- I have access to my server: Through SSH and direct access
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: 0.2.7

### Steps to reproduce

- Install Wireguard, then reboot
- Uninstall Wireguard
- Run YunoHost's diagnosis tool (from CLI it can be done with `sudo yunohost diagnosis run`)

### Expected behavior

Wireguard should be uninstalled clearly, leaving no leftover configurations on YunoHost's internal database.

### Logs

`sudo yunohost diagnosis show --issues`

```
reports: 
  0: 
    description: Ports exposure
    id: ports
    items: 
      0: 
        details: 
          - Exposing this port is needed for [?] features (service wireguard)
          - To fix this issue, you most probably need to configure port forwarding on your internet router as described in https://yunohost.org/isp_box_config
        status: ERROR
        summary: Port 8098 is not reachable from outside.
  1: 
    description: Web
    id: web
    items: 
      0: 
        details: Timed-out while trying to contact your server from outside. It appears to be unreachable.
1. The most common cause for this issue is that port 80 (and 443) are not correctly forwarded to your server.
2. You should also make sure that the service nginx is running
3. On more complex setups: make sure that no firewall or reverse-proxy is interfering.
        status: ERROR
        summary: Domain block.azkware.net appears unreachable through HTTP from outside the local network.
  2: 
    description: Services status check
    id: services
    items: 
      0: 
        details: You can try to restart the service, and if it doesn't work, have a look at the service logs in the webadmin (from the command line, you can do this with 'yunohost service restart wireguard' and 'yunohost service log wireguard').
        status: WARNING
        summary: Service wireguard is unknown :(
```
